# Generated by Django 2.1.3 on 2018-11-22 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181122_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sender',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User'),
            preserve_default=False,
        ),
    ]
